### PR TITLE
tasklogger v1.0.0, exclude py2

### PR DESCRIPTION
**Pull request by scottgigante**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by scottgigante** [comment]
@conda-forge-admin, please rerender

**Comment by scottgigante** [comment]
@bebatut is there anything more I need to do to make this merge?

**Comment by djsutherland** [comment]
@scottgigante The merging process is manual; either a maintainer – or when, an intervention is needed, someone from core – needs to click the merge button. Since it seems that @bebatut isn't actively maintaining the feedstock anymore, though, I'm going to go ahead and merge it.

You'll be [added as a maintainer](https://conda-forge.org/docs/maintainer/adding_pkgs.html#maintainer-role) and able to merge PRs / etc in the future. Feel free to ping @conda-forge/core or ask on gitter / the mailing list if you need help with anything going forward. :)

**Comment by scottgigante** [comment]
Thanks @dougalsutherland !

**Pull request merged**
